permalink: /:year/:month/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
markdown: kramdown
name: "tjun memo"
description: "tjunのメモ"
url: http://tjun.jp/blog
