permalink: /blog/:year/:month/:title
exclude: [".gitignore", "README.md", ".sass-cache", ".DS_Store","changelog.md", "Rakefile", "Gemfile", "Gemfile.lock", "Capfile", "config"]
#highlighter: rouge
highlighter: pygments
markdown: redcarpet
name: "tjun memo"
description: "tjunのメモ"
url: http://tjun.org

sass:
    style: :compressed

elasticsearch:
    host: "localhost:9200"
    index: "blog"
    type: "post"
    analyzer: "kuromoji"

gems:
 - jemoji
