permalink: /blog/:year/:month/:title
exclude: [".gitignore", "README.md", ".sass-cache", ".DS_Store","changelog.md", "Rakefile", "Gemfile", "Gemfile.lock", "Capfile", "config"]
pygments: true
#markdown: kramdown
markdown: redcarpet
name: "tjun memo"
description: "tjunのメモ"
url: http://tjun.org
